# BareOS Director with MariaDB

version: '2'

services:
  bareos-dir:
    image: samma/bareos-dir:20 
    hostname: bareos-dir
    ports:
      - 9101:9101
    environment:
      DBDRIVER: postgresql 
      PGHOST: bareos-db
      PGDATABASE: bareos
      PGUSER: bareos
      PGPORT: 5432
      PGPASSWORD: titok
      MAILUSER: techinfo@webandservice.hu
      MAILHUB: phoenix.webandsevice.lan
      MAILDOMAIN: webandservice.hu
      MAILHOSTNAME: bareos-dir.webandsevice.lan
      WEBADMINUSER: admin
      WEBADMINPASS: admin
    links:
      - bareos-db:bareos-db
    volumes:
      - bareos-etc:/etc/bareos
      - bareos-log:/var/log/bareos
    tmpfs: 
      - /run:rw,noexec,nosuid,size=65536k
      - /tmp:rw,noexec,nosuid,size=1g
    depends_on:
      - bareos-db
  bareos-db:
    image: postgres:12.7-alpine 
    env_file:
      - .postgres_env
    volumes:
      - db-data:/var/lib/postgresql/data
  bareos-webui:
    image: samma/bareos-webui:20 
    ports:
      - 9180:80
    environment:
      DIRADDRESS: bareos-dir
      DIRPORT: 9101
    links:
      - bareos-dir:bareos-dir
    depends_on:
      - bareos-dir
volumes:
  bareos-etc:
  bareos-log:
  db-data:
